// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rango.API.DbContexts;

#nullable disable

namespace Rango.API.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    partial class RecipesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("IngredientRecipe");

                    b.HasData(
                        new
                        {
                            IngredientsId = 1,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 2,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 3,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 4,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 5,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 6,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 7,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 8,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 14,
                            RecipesId = 1
                        },
                        new
                        {
                            IngredientsId = 9,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 19,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 11,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 12,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 13,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 2,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 21,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 8,
                            RecipesId = 2
                        },
                        new
                        {
                            IngredientsId = 1,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 12,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 17,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 14,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 2,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 16,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 23,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 8,
                            RecipesId = 3
                        },
                        new
                        {
                            IngredientsId = 1,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 18,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 16,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 20,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 22,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 2,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 21,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 8,
                            RecipesId = 4
                        },
                        new
                        {
                            IngredientsId = 24,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 10,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 23,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 2,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 12,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 18,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 14,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 20,
                            RecipesId = 5
                        },
                        new
                        {
                            IngredientsId = 13,
                            RecipesId = 5
                        });
                });

            modelBuilder.Entity("Rango.API.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carne de Vaca"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cebola"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cerveja Escura"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fatia de Pão Integral"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mostarda"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Chicória"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Maionese"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vários Temperos"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mexilhões"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aipo"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Batatas Fritas"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tomate"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Extrato de Tomate"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Folha de Louro"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cenoura"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Alho"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Vinho Tinto"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Leite de Coco"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Gengibre"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Pimenta Malagueta"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Tamarindo"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Peixe Firme"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Pasta de Gengibre e Alho"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Garam Masala"
                        });
                });

            modelBuilder.Entity("Rango.API.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ensopado Flamengo de Carne de Vaca com Chicória"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mexilhões com Batatas Fritas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ragu alla Bolognese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rendang"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Masala de Peixe"
                        });
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("Rango.API.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rango.API.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
